# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hpcuiapi.models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256, null=True)),
                ('file', models.FileField(storage=hpcuiapi.models.MediaFileSystemStorage(), upload_to=hpcuiapi.models.media_file_name)),
                ('md5sum', models.CharField(max_length=36)),
                ('size', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('params', jsonfield.fields.JSONField(default=[])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToolFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=hpcuiapi.models.tool_file_name)),
                ('exe', models.BooleanField(default=False)),
                ('size', models.IntegerField(null=True)),
                ('filename', models.CharField(max_length=256, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpcuiapi.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', jsonfield.fields.JSONField(default=[])),
                ('input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hpcuiapi.WorkflowStep')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpcuiapi.Project')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpcuiapi.Tool')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpcuiapi.Project'),
        ),
    ]
