# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import hpcuiapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('hpcuiapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolfile',
            name='filename',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='toolfile',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='toolfile',
            name='file',
            field=models.FileField(upload_to=hpcuiapi.models.tool_file_name),
        ),
    ]
