# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpcuiapi', '0003_auto_20160330_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkflowStep',
            new_name='Task',
        ),
    ]
