# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hpcuiapi', '0004_auto_20160507_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.TextField(default=datetime.datetime(2016, 5, 7, 18, 0, 25, 114583, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
